name: EditorConfig check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: wow-rp-addons/actions-editorconfig-check@v1.0.2
        with:
          files: $(git ls-files '*.js' '*.jsx' '*.json' '*md' '*yml' '*.html')